---
# These tasks install Apache.

- name: Install Apache
  become: true
  apt: name={{ item }} state=present
  with_items:
   - apache2

- name: Start Apache Service
  become: true
  service: name=apache2 state=started enabled=yes

- name: add vagrant user to www-data group
  become: true
  user:
    name: vagrant
    group: www-data

- name: Change the DocumentRoot path
  become: true
  template: src=000-default.conf.j2 dest=/etc/apache2/sites-available/000-default.conf
  notify: restart apache